# Generated by Django 2.2.4 on 2024-01-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240107_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='img',
            field=models.CharField(default='https://as1.ftcdn.net/v2/jpg/03/39/45/96/1000_F_339459697_XAFacNQmwnvJRqe1Fe9VOptPWMUxlZP8.jpg', max_length=225),
        ),
    ]
